### ISSUE TITLE
SyntaxError when webpacking due to unsupported arrow functions by uglify

### ISSUE THREAD

**Issue by portwatcher** [dubov94/vue-jwt-mongo#3]
The official vue-cli will generate a project where `/node_modules/` is excluded by `babel-loader` in webpack config file.

When run `npm run build`, client.js will be handled by Unglify without being babel-transcripted first.

It's better to publish a `/dist` folder where all babel-transcripted files locate, and export these files to work smoothly with official vue-cli boilerplate.

By the way, this is a really nice repo and save me a lot of time! Thank you!

**Comment by dubov94** [comment]
Thanks for the report! I will look into the issue soon.
